services:
  back:
    container_name: back
    build: .
    restart: always
    networks:
    - proxy_default

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - proxy_default

volumes:
  postgres_data:

networks:
  proxy_default:
    external: true
